# Generated by Django 4.2.21 on 2025-06-14 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_id', models.IntegerField(unique=True)),
                ('category_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.IntegerField(unique=True)),
                ('date_time', models.DateTimeField()),
                ('full_date', models.CharField(max_length=100)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DimOrderRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_region_id', models.IntegerField(unique=True)),
                ('order_region_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DimShippingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_mode_id', models.IntegerField(unique=True)),
                ('shipping_mode_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FactShipping',
            fields=[
                ('shipping_fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_delay', models.FloatField()),
                ('is_late', models.BooleanField()),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimdate')),
                ('order_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimorderregion')),
                ('shipping_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimshippingmode')),
            ],
        ),
        migrations.CreateModel(
            name='FactSales',
            fields=[
                ('sales_fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_value', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimcategory')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimdate')),
                ('order_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimorderregion')),
                ('shipping_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimshippingmode')),
            ],
        ),
        migrations.CreateModel(
            name='FactProfit',
            fields=[
                ('profit_fact_id', models.AutoField(primary_key=True, serialize=False)),
                ('profit_value', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimcategory')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimdate')),
                ('order_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimorderregion')),
                ('shipping_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bi.dimshippingmode')),
            ],
        ),
    ]
